// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarWin.Data;

#nullable disable

namespace SolarWin.Data.Migrations
{
    [DbContext(typeof(SolarWinDbContext))]
    [Migration("20260724114248_InitialChatMessages")]
    partial class InitialChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SolarWin.Data.Entities.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Ciphertext")
                        .HasColumnType("BLOB");

                    b.Property<string>("ClientMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EncryptionEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EncryptionHeader")
                        .HasColumnType("BLOB");

                    b.Property<string>("EncryptionMessageType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionScheme")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptionSignature")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("ForwardedMessageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepliedMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoomSequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("RoomId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_messages_room_client")
                        .HasFilter("ClientMessageId IS NOT NULL AND ClientMessageId != ''");

                    b.HasIndex("RoomId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_messages_room_created");

                    b.HasIndex("RoomId", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_messages_room_msgid")
                        .HasFilter("MessageId != '00000000-0000-0000-0000-000000000000'");

                    b.HasIndex("RoomId", "RoomSequence", "MessageId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_messages_room_seq_id");

                    b.ToTable("chat_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
